/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.reader.csvreader;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GenericSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1071306948507988793L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GenericSchema\",\"namespace\":\"com.reader.csvreader\",\"fields\":[{\"name\":\"col1\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence col1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GenericSchema() {}

  /**
   * All-args constructor.
   * @param col1 The new value for col1
   */
  public GenericSchema(java.lang.CharSequence col1) {
    this.col1 = col1;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return col1;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: col1 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'col1' field.
   * @return The value of the 'col1' field.
   */
  public java.lang.CharSequence getCol1() {
    return col1;
  }

  /**
   * Sets the value of the 'col1' field.
   * @param value the value to set.
   */
  public void setCol1(java.lang.CharSequence value) {
    this.col1 = value;
  }

  /**
   * Creates a new GenericSchema RecordBuilder.
   * @return A new GenericSchema RecordBuilder
   */
  public static com.reader.csvreader.GenericSchema.Builder newBuilder() {
    return new com.reader.csvreader.GenericSchema.Builder();
  }

  /**
   * Creates a new GenericSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GenericSchema RecordBuilder
   */
  public static com.reader.csvreader.GenericSchema.Builder newBuilder(com.reader.csvreader.GenericSchema.Builder other) {
    return new com.reader.csvreader.GenericSchema.Builder(other);
  }

  /**
   * Creates a new GenericSchema RecordBuilder by copying an existing GenericSchema instance.
   * @param other The existing instance to copy.
   * @return A new GenericSchema RecordBuilder
   */
  public static com.reader.csvreader.GenericSchema.Builder newBuilder(com.reader.csvreader.GenericSchema other) {
    return new com.reader.csvreader.GenericSchema.Builder(other);
  }

  /**
   * RecordBuilder for GenericSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GenericSchema>
    implements org.apache.avro.data.RecordBuilder<GenericSchema> {

    private java.lang.CharSequence col1;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.reader.csvreader.GenericSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.col1)) {
        this.col1 = data().deepCopy(fields()[0].schema(), other.col1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing GenericSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.reader.csvreader.GenericSchema other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.col1)) {
        this.col1 = data().deepCopy(fields()[0].schema(), other.col1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'col1' field.
      * @return The value.
      */
    public java.lang.CharSequence getCol1() {
      return col1;
    }

    /**
      * Sets the value of the 'col1' field.
      * @param value The value of 'col1'.
      * @return This builder.
      */
    public com.reader.csvreader.GenericSchema.Builder setCol1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.col1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'col1' field has been set.
      * @return True if the 'col1' field has been set, false otherwise.
      */
    public boolean hasCol1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'col1' field.
      * @return This builder.
      */
    public com.reader.csvreader.GenericSchema.Builder clearCol1() {
      col1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public GenericSchema build() {
      try {
        GenericSchema record = new GenericSchema();
        record.col1 = fieldSetFlags()[0] ? this.col1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
